FROM dumptec/php-fpm:8.1-base
MAINTAINER "dump" <ola@dump.tec.br>

### Add xdebug config
COPY ./data/php-ini.d/php-8.1-xdebug.ini /usr/local/etc/php/conf.d/zz-php-8.1-xdebug.ini

## Install extension dependencies
RUN apt install -y --allow-downgrades procps libcurl4-openssl-dev \
    libssl1.1=1.1.1n-0+deb11u1 libxml2=2.9.10+dfsg-6.7+deb11u1 \
    libpq-dev libxml2-dev libssl-dev libzip-dev zlib1g=1:1.2.11.dfsg-2 libsodium-dev libpng-dev

## Install required dependencies
RUN docker-php-ext-install bcmath pdo_pgsql simplexml zip gd sodium \
    && docker-php-ext-enable gd sodium bcmath pdo_pgsql simplexml zip

## local dependencies
RUN apt install -y npm \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug > /dev/null 2>&1

## Install composer
WORKDIR /tmp
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer
WORKDIR /app
