FROM php:8.1-fpm
MAINTAINER "dump" <ola@dump.tec.br>

## Create dump user
RUN useradd -ms /bin/bash dump

## Change Timezone
RUN ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

## Set default debian repo
RUN echo "deb http://deb.debian.org/debian bullseye main" > /etc/apt/sources.list

## Update/upgrade apt repo
RUN apt update -y && apt upgrade -y