version: "3.7"

services:

    phpfpm:
        image: dumptec/php-fpm:dev-8.1-latest
        container_name: phpfpm
        working_dir: /app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: on-failure
        ports:
            - "22:22"
        logging:
            options:
                max-size: "50m"
                max-file: "3"
        volumes:
            - ./app:/app

