FROM dumptec/php-fpm:8.1-base

## Install extension dependencies
RUN apt install -y --allow-downgrades \
    libcurl4=7.74.0-1.3+deb11u1  libcurl4-openssl-dev \
    procps  libssl1.1 libxml2 \
    libpq-dev libxml2-dev libssl-dev libzip-dev zlib1g libsodium-dev libpng-dev \
## Install required dependencies
    && docker-php-ext-install sockets bcmath pgsql pdo_pgsql simplexml zip gd sodium \
    && docker-php-ext-enable gd sodium bcmath pgsql pdo_pgsql simplexml zip 

WORKDIR /app
